### ISSUE TITLE
Store and retrieve rationals in sqlite via diesel

### ISSUE THREAD

**Issue by maghoff** [revolverhuset/sharebill-riir-again#2]
See the [Theme](https://github.com/maghoff/sausagewiki/blob/master/src/theme.rs) type in Sausagewiki for inspiration.

**Comment by maghoff** [comment]
We'll also want to implement support for SUM in a way that sqlite understands, and I have the feeling I've done somthing along those lines before. Maybe I'm just thinking about the rust functions I have exposed to sqlite in sausagewiki: <https://github.com/maghoff/sausagewiki/blob/master/src/db.rs#L28-L36>

**Comment by johshoff** [comment]
Rational type introduced c5430a4d113580fb666a9c33d25f00cd5ae3f8f8. Just needs to actually be used in the application and tables.

Could use some sanity checking for inputs (from sqlite), but otherwise good to go.

**Comment by johshoff** [comment]
Added checking for valid input in #6. Plz to review or modify directly 🙂
